version: '2.1'

services:
  bind:
    image: sameersbn/bind:latest
    environment:
      - ROOT_PASSWORD=ubuntu
    
    volumes:
      - /srv/docker/bind:/data
    networks:
      redDNS:
        ipv4_address: 192.168.1.5
        ipv6_address: 2001:b:b:b::2

networks:
  redDNS:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
        - subnet: 2001:b:b:b::/64
